(deftheme gruvbox "The Gruvbox color theme.")

(let* ((class '((type graphic)))
       (gruvbox-dark0_hard "#1d2021")
       (gruvbox-dark0 "#282828")
       (gruvbox-dark0_soft "#32302f")
       (gruvbox-dark1 "#3c3836")
       (gruvbox-dark2 "#504945")
       (gruvbox-dark3 "#665c54")
       (gruvbox-dark4 "#7c6f64")
       (gruvbox-bg gruvbox-dark0_hard)
       (gruvbox-gray "#928374")
       (gruvbox-light0_hard "#ffffc8")
       (gruvbox-light0 "#fdf4c1")
       (gruvbox-light1 "#ebdbb2")
       (gruvbox-light2 "#d5c4a1")
       (gruvbox-light3 "#bdae93")
       (gruvbox-light4 "#a89984")
       (gruvbox-bright_red "#fb4933")
       (gruvbox-bright_green "#b8bb26")
       (gruvbox-bright_yellow "#fabd2f")
       (gruvbox-bright_blue "#83a598")
       (gruvbox-bright_purple "#d3869b")
       (gruvbox-bright_aqua "#8ec07c")
       (gruvbox-bright_orange "#fe8019")
       (gruvbox-neutral_red "#fb4934")
       (gruvbox-neutral_green "#b8bb26")
       (gruvbox-neutral_yellow "#fabd2f")
       (gruvbox-neutral_blue "#83a598")
       (gruvbox-neutral_purple "#d3869b")
       (gruvbox-neutral_aqua "#8ec07c")
       (gruvbox-neutral_orange "#fe8019")
       (gruvbox-faded_red "#cc241d")
       (gruvbox-faded_green "#98971a")
       (gruvbox-faded_yellow "#d79921")
       (gruvbox-faded_blue "#458588")
       (gruvbox-faded_purple "#b16286")
       (gruvbox-faded_aqua "#689d6a")
       (gruvbox-faded_orange "#d65d0e")
       (gruvbox-dark_red "#421E1E")
       (gruvbox-dark_blue "#2B3C44")
       (gruvbox-dark_aqua "#36473A")
       (gruvbox-white "#FFFFFF")
       (gruvbox-black "#000000")
       (gruvbox-sienna "#DD6F48")
       (gruvbox-lightblue4 "#66999D")
       (gruvbox-burlywood4 "#BBAA97")
       (gruvbox-aquamarine4 "#83A598")
       (gruvbox-turquoise4 "#61ACBB"))
  
  (custom-theme-set-faces
   'gruvbox

   `(default ((,class (:background ,gruvbox-bg :foreground ,gruvbox-light1))))
   `(error ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(success ((,class (:foreground ,gruvbox-bright_green :bold t))))
   `(warning ((,class (:foreground ,gruvbox-bright_yellow :bold t))))
   `(alert-low-face ((,class (:foreground ,gruvbox-bright_blue))))
   `(trailing-whitespace ((,class (:background ,gruvbox-bright_red))))
   `(escape-glyph ((,class (:foreground ,gruvbox-bright_aqua))))
   `(header-line ((,class (:background ,gruvbox-dark0 :foreground ,gruvbox-light3 :box nil :nil))))
   `(highlight ((,class (:underline t :extend t))))
   `(homoglyph ((,class (:foreground ,gruvbox-lightblue4 :bold t))))
   `(match ((,class (:inherit highlight))))
   `(cursor ((,class (:background ,gruvbox-light1))))
   `(mode-line ((,class (:background ,gruvbox-dark1))))
   `(mode-line-inactive ((,class (:background ,gruvbox-dark0_soft))))
   `(fringe ((,class (:background ,gruvbox-bg))))
   `(hl-line ((,class (:background ,gruvbox-dark0_soft :extend t))))
   `(region ((,class (:background ,gruvbox-dark1 :extend t))))
   `(secondary-selection ((,class (:background ,gruvbox-dark1))))
   `(minibuffer-prompt ((,class (:foreground ,gruvbox-bright_yellow))))
   `(vertical-border ((,class (:foreground ,gruvbox-dark2))))
   `(internal-border ((,class (:background ,gruvbox-dark2))))
   `(window-divider ((,class (:foreground ,gruvbox-dark2))))
   `(link ((,class (:foreground ,gruvbox-faded_blue :underline t))))
   `(shadow ((,class (:foreground ,gruvbox-dark4))))
   `(tooltip ((,class (:foreground ,gruvbox-light1 :background ,gruvbox-dark1))))

   ;; Built-in syntax
   `(font-lock-builtin-face ((,class (:foreground ,gruvbox-bright_orange))))
   `(font-lock-constant-face ((,class (:foreground ,gruvbox-bright_purple))))
   `(font-lock-comment-face ((,class (:foreground ,gruvbox-dark4))))
   `(font-lock-function-name-face ((,class (:foreground ,gruvbox-bright_yellow))))
   `(font-lock-keyword-face ((,class (:foreground ,gruvbox-bright_red))))
   `(font-lock-string-face ((,class (:foreground ,gruvbox-bright_green))))
   `(font-lock-number-face ((,class (:foreground ,gruvbox-bright_purple))))
   `(font-lock-variable-name-face ((,class (:foreground ,gruvbox-bright_blue))))
   `(font-lock-type-face ((,class (:foreground ,gruvbox-bright_purple))))
   `(font-lock-property-face ((,class (:foreground ,gruvbox-bright_blue))))
   `(font-lock-warning-face ((,class (:foreground ,gruvbox-bright_red :bold t))))

   ;; Completions
   `(completions-common-part ((,class (:inherit match))))
   `(completions-annotations ((,class (:inherit shadow :italic t))))

   ;; Customize faces
   `(widget-field ((,class (:background ,gruvbox-dark3))))
   `(custom-group-tag ((,class (:foreground ,gruvbox-bright_blue :weight bold))))
   `(custom-variable-tag ((,class (:foreground ,gruvbox-bright_blue :weight bold))))
   
   ;; line numbers
   `(line-number ((,class (:inherit default :foreground ,gruvbox-dark4))))
   `(line-number-current-line ((,class (:inherit line-number :foreground ,gruvbox-neutral_yellow :background ,gruvbox-dark0_soft))))

   ;; show-paren
   `(show-paren-match ((,class (:background ,gruvbox-dark1 :bold t))))
   `(show-paren-mismatch ((,class (:inherit show-paren-match :background ,gruvbox-bright_red))))

   ;; Highlight indentation mode
   `(highlight-indentation-current-column-face ((,class (:background ,gruvbox-dark2))))
   `(highlight-indentation-face ((,class (:background ,gruvbox-dark1))))

   ;; whitespace-mode
   `(whitespace-space ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))
   `(whitespace-hspace ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))
   `(whitespace-tab ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))
   `(whitespace-newline ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))
   `(whitespace-trailing ((,class (:background ,gruvbox-dark1 :foreground ,gruvbox-bright_red))))
   `(whitespace-line ((,class (:background ,gruvbox-dark1 :foreground ,gruvbox-bright_red))))
   `(whitespace-space-before-tab ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))
   `(whitespace-indentation ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))
   `(whitespace-empty ((,class (:background unspecified :foreground unspecified))))
   `(whitespace-space-after-tab ((,class (:background ,gruvbox-bg :foreground ,gruvbox-dark4))))

   ;; RainbowDelimiters
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,gruvbox-turquoise4))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground ,gruvbox-bright_purple))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground ,gruvbox-bright_green))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground ,gruvbox-bright_orange))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground ,gruvbox-bright_yellow))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground ,gruvbox-bright_aqua))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground ,gruvbox-bright_blue))))
   `(rainbow-delimiters-depth-8-face ((,class (:inherit rainbow-delimiters-depth-2-face))))
   `(rainbow-delimiters-depth-9-face ((,class (:inherit rainbow-delimiters-depth-3-face))))
   `(rainbow-delimiters-depth-10-face ((,class (:inherit rainbow-delimiters-depth-4-face))))
   `(rainbow-delimiters-depth-11-face ((,class (:inherit rainbow-delimiters-depth-5-face))))
   `(rainbow-delimiters-depth-12-face ((,class (:inherit rainbow-delimiters-depth-6-face))))
   `(rainbow-delimiters-unmatched-face ((,class (:inherit show-paren-mismatch))))

   ;; Diffs
   `(diff-header ((,class (:background ,gruvbox-dark1))))
   `(diff-file-header ((,class (:background ,gruvbox-dark2))))
   `(diff-hunk-header ((,class (:background ,gruvbox-dark2))))
   `(diff-context ((,class (:background ,gruvbox-dark1 :foreground ,gruvbox-light1))))
   `(diff-added ((,class (:background unspecified :foreground ,gruvbox-neutral_green))))
   `(diff-refine-added ((,class (:background ,gruvbox-faded_green :foreground ,gruvbox-light1))))
   `(diff-removed ((,class (:background unspecified :foreground ,gruvbox-neutral_red))))
   `(diff-refine-removed ((,class (:background ,gruvbox-faded_red :foreground ,gruvbox-light1))))
   `(diff-indicator-changed ((,class (:inherit 'diff-changed))))
   `(diff-indicator-added ((,class (:inherit 'diff-added))))
   `(diff-indicator-removed ((,class (:inherit 'diff-removed))))

   ;; Ediff
   `(ediff-even-diff-A ((,class (:background ,gruvbox-dark1))))
   `(ediff-even-diff-B ((,class (:background ,gruvbox-dark1))))
   `(ediff-even-diff-C ((,class (:background ,gruvbox-dark1))))
   `(ediff-even-diff-Ancestor ((,class (:background ,gruvbox-dark1))))
   `(ediff-odd-diff-A ((,class (:background ,gruvbox-dark2))))
   `(ediff-odd-diff-B ((,class (:background ,gruvbox-dark2))))
   `(ediff-odd-diff-C ((,class (:background ,gruvbox-dark2))))
   `(ediff-odd-diff-Ancestor ((,class (:background ,gruvbox-dark2))))
   `(ediff-fine-diff-A ((,class (:background ,gruvbox-bright_green))))
   `(ediff-fine-diff-Ancestor ((,class (:background ,gruvbox-bright_aqua))))
   `(ediff-fine-diff-B ((,class (:background ,gruvbox-faded_green))))
   `(ediff-fine-diff-C ((,class (:background ,gruvbox-turquoise4))))
   `(ediff-current-diff-A ((,class (:background ,gruvbox-bright_red))))
   `(ediff-current-diff-Ancestor ((,class (:background ,gruvbox-faded_blue))))
   `(ediff-current-diff-B ((,class (:background ,gruvbox-faded_red))))
   `(ediff-current-diff-C ((,class (:background ,gruvbox-faded_purple))))

   ;; popup
   `(popup-face ((,class (:underline nil :foreground ,gruvbox-light1 :background ,gruvbox-dark1))))
   `(popup-menu-mouse-face ((,class (:underline nil :foreground ,gruvbox-light0 :background ,gruvbox-faded_green))))
   `(popup-menu-selection-face ((,class (:underline nil :foreground ,gruvbox-light0 :background ,gruvbox-faded_green))))
   `(popup-tip-face ((,class (:underline nil :foreground ,gruvbox-light2 :background ,gruvbox-dark2))))

   ;; helm
   `(helm-M-x-key ((,class (:foreground ,gruvbox-bright_orange))))
   `(helm-action ((,class (:foreground ,gruvbox-light0_hard :underline t))))
   `(helm-bookmark-addressbook ((,class (:foreground ,gruvbox-bright_red))))
   `(helm-bookmark-directory ((,class (:foreground ,gruvbox-bright_purple))))
   `(helm-bookmark-file ((,class (:foreground ,gruvbox-faded_blue))))
   `(helm-bookmark-gnus ((,class (:foreground ,gruvbox-faded_purple))))
   `(helm-bookmark-info ((,class (:foreground ,gruvbox-turquoise4))))
   `(helm-bookmark-man ((,class (:foreground gruvbox-sienna))))
   `(helm-bookmark-w3m ((,class (:foreground ,gruvbox-bright_yellow))))
   `(helm-buffer-directory ((,class (:foreground gruvbox-white :background ,gruvbox-bright_blue))))
   `(helm-buffer-not-saved ((,class (:foreground ,gruvbox-faded_red))))
   `(helm-buffer-process ((,class (:foreground gruvbox-burlywood4))))
   `(helm-buffer-saved-out ((,class (:foreground ,gruvbox-bright_red))))
   `(helm-buffer-size ((,class (:foreground ,gruvbox-bright_purple))))
   `(helm-candidate-number ((,class (:foreground ,gruvbox-bright_green))))
   `(helm-eshell-prompts-buffer-name ((,class (:foreground ,gruvbox-bright_green))))
   `(helm-eshell-prompts-promptidx ((,class (:foreground ,gruvbox-turquoise4))))
   `(helm-ff-directory ((,class (:foreground ,gruvbox-bright_purple))))
   `(helm-ff-executable ((,class (:foreground ,gruvbox-turquoise4))))
   `(helm-ff-file ((,class (:foreground gruvbox-sienna))))
   `(helm-ff-invalid-symlink ((,class (:foreground gruvbox-white :background ,gruvbox-bright_red))))
   `(helm-ff-prefix ((,class (:foreground ,gruvbox-black :background ,gruvbox-bright_yellow))))
   `(helm-ff-symlink ((,class (:foreground ,gruvbox-bright_orange))))
   `(helm-grep-cmd-line ((,class (:foreground ,gruvbox-bright_green))))
   `(helm-grep-file ((,class (:foreground ,gruvbox-faded_purple))))
   `(helm-grep-finish ((,class (:foreground ,gruvbox-turquoise4))))
   `(helm-grep-lineno ((,class (:foreground ,gruvbox-bright_orange))))
   `(helm-grep-match ((,class (:foreground ,gruvbox-bright_yellow))))
   `(helm-grep-running ((,class (:foreground ,gruvbox-bright_red))))
   `(helm-header ((,class (:foreground gruvbox-aquamarine4))))
   `(helm-helper ((,class (:foreground gruvbox-aquamarine4))))
   `(helm-history-deleted ((,class (:foreground ,gruvbox-black :background ,gruvbox-bright_red))))
   `(helm-history-remote ((,class (:foreground ,gruvbox-faded_red))))
   `(helm-lisp-completion-info ((,class (:foreground ,gruvbox-faded_orange))))
   `(helm-lisp-show-completion ((,class (:foreground ,gruvbox-bright_red))))
   `(helm-locate-finish ((,class (:foreground gruvbox-white :background gruvbox-aquamarine4))))
   `(helm-match ((,class (:foreground ,gruvbox-bright_orange))))
   `(helm-moccur-buffer ((,class (:foreground ,gruvbox-bright_aqua :underline t))))
   `(helm-prefarg ((,class (:foreground ,gruvbox-turquoise4))))
   `(helm-selection ((,class (:foreground gruvbox-white :background ,gruvbox-dark2))))
   `(helm-selection-line ((,class (:foreground gruvbox-white :background ,gruvbox-dark2))))
   `(helm-separator ((,class (:foreground ,gruvbox-faded_red))))
   `(helm-source-header ((,class (:foreground ,gruvbox-light2))))
   `(helm-visible-mark ((,class (:foreground ,gruvbox-black :background ,gruvbox-light3))))
   `(helm-rg-preview-line-highlight ((,class (:foreground ,gruvbox-black :background ,gruvbox-bright_green))))
   `(helm-rg-base-rg-cmd-face ((,class (:foreground ,gruvbox-light2))))
   `(helm-rg-extra-arg-face ((,class (:foreground ,gruvbox-bright_yellow))))
   `(helm-rg-inactive-arg-face ((,class (:foreground ,gruvbox-faded_aqua))))
   `(helm-rg-active-arg-face ((,class (:foreground ,gruvbox-bright_green))))
   `(helm-rg-directory-cmd-face ((,class (:foreground gruvbox-burlywood4 :background ,gruvbox-black))))
   `(helm-rg-error-message ((,class (:foreground ,gruvbox-bright_red))))
   `(helm-rg-title-face ((,class (:foreground ,gruvbox-bright_purple))))
   `(helm-rg-directory-header-face ((,class (:foreground gruvbox-white :background ,gruvbox-dark1))))
   `(helm-rg-file-match-face ((,class (:foreground ,gruvbox-turquoise4))))
   `(helm-rg-colon-separator-ripgrep-output-face ((,class (:foreground ,gruvbox-dark3 :background ,gruvbox-bg))))
   `(helm-rg-line-number-match-face ((,class (:foreground ,gruvbox-faded_orange))))
   `(helm-rg-match-text-face ((,class (:foreground gruvbox-white :background ,gruvbox-bright_purple))))

   ;; hi-lock-mode
   `(hi-black-b ((,class (:foreground ,gruvbox-black :weight bold))))
   `(hi-black-hb ((,class (:foreground ,gruvbox-black :weight bold :height 1.5))))
   `(hi-blue ((,class (:foreground ,gruvbox-dark0 :background ,gruvbox-bright_blue))))
   `(hi-blue-b ((,class (:foreground ,gruvbox-bright_blue :weight bold))))
   `(hi-green ((,class (:foreground ,gruvbox-dark0 :background ,gruvbox-bright_green))))
   `(hi-green-b ((,class (:foreground ,gruvbox-bright_green :weight bold))))
   `(hi-pink ((,class (:foreground ,gruvbox-dark0 :background ,gruvbox-bright_purple))))
   `(hi-red-b ((,class (:foreground ,gruvbox-bright_red :weight bold))))
   `(hi-yellow ((,class (:foreground ,gruvbox-dark0 :background ,gruvbox-faded_yellow))))

   ;; company-mode
   `(company-scrollbar-bg ((,class (:background ,gruvbox-dark2))))
   `(company-scrollbar-fg ((,class (:background ,gruvbox-dark1))))
   `(company-tooltip ((,class (:background ,gruvbox-dark0))))
   `(company-tooltip-annotation ((,class (:inherit completions-annotations))))
   `(company-tooltip-annotation-selection ((,class (:inherit 'company-tooltip-annotation))))
   `(company-tooltip-selection ((,class (:background ,gruvbox-dark1))))
   `(company-tooltip-common ((,class (:inherit match))))
   `(company-tooltip-common-selection ((,class (:inherit company-tooltip-common))))
   `(company-preview-common ((,class (:foreground ,gruvbox-light0))))
   `(company-preview ((,class (:inherit match :background ,gruvbox-dark0_soft))))
   `(company-preview-search ((,class (:background ,gruvbox-turquoise4))))
   `(company-template-field ((,class (:foreground ,gruvbox-black :background ,gruvbox-bright_yellow))))
   `(company-echo-common ((,class (:foreground ,gruvbox-faded_red))))

   ;; term
   `(term-color-black ((,class (:foreground ,gruvbox-dark2 :background ,gruvbox-dark1))))
   `(term-color-blue ((,class (:foreground ,gruvbox-bright_blue :background ,gruvbox-bright_blue))))
   `(term-color-cyan ((,class (:foreground ,gruvbox-bright_aqua :background ,gruvbox-bright_aqua))))
   `(term-color-green ((,class (:foreground ,gruvbox-bright_green :background ,gruvbox-bright_green))))
   `(term-color-magenta ((,class (:foreground ,gruvbox-bright_purple :background ,gruvbox-bright_purple))))
   `(term-color-red ((,class (:foreground ,gruvbox-bright_red :background ,gruvbox-bright_red))))
   `(term-color-white ((,class (:foreground ,gruvbox-light1 :background ,gruvbox-light1))))
   `(term-color-yellow ((,class (:foreground ,gruvbox-bright_yellow :background ,gruvbox-bright_yellow))))
   `(term-default-fg-color ((,class (:foreground ,gruvbox-light0))))
   `(term-default-bg-color ((,class (:background ,gruvbox-bg))))

   ;; message-mode
   `(message-header-to ((,class (:inherit 'font-lock-variable-name-face))))
   `(message-header-cc ((,class (:inherit 'font-lock-variable-name-face))))
   `(message-header-subject ((,class (:foreground ,gruvbox-bright_orange :weight bold))))
   `(message-header-newsgroups ((,class (:foreground ,gruvbox-bright_yellow :weight bold))))
   `(message-header-other ((,class (:inherit 'font-lock-variable-name-face))))
   `(message-header-name ((,class (:inherit 'font-lock-keyword-face))))
   `(message-header-xheader ((,class (:foreground ,gruvbox-faded_blue))))
   `(message-separator ((,class (:inherit 'font-lock-comment-face))))
   `(message-cited-text ((,class (:inherit 'font-lock-comment-face))))
   `(message-mml ((,class (:foreground ,gruvbox-faded_green :weight bold))))

   ;; org-mode
   `(org-hide ((,class (:foreground ,gruvbox-dark0))))
   `(org-level-1 ((,class (:foreground ,gruvbox-bright_blue))))
   `(org-level-2 ((,class (:foreground ,gruvbox-bright_yellow))))
   `(org-level-3 ((,class (:foreground ,gruvbox-bright_purple))))
   `(org-level-4 ((,class (:foreground ,gruvbox-bright_red))))
   `(org-level-5 ((,class (:foreground ,gruvbox-bright_green))))
   `(org-level-6 ((,class (:foreground ,gruvbox-bright_aqua))))
   `(org-level-7 ((,class (:foreground ,gruvbox-faded_blue))))
   `(org-level-8 ((,class (:foreground ,gruvbox-bright_orange))))
   `(org-special-keyword ((,class (:inherit 'font-lock-comment-face))))
   `(org-drawer ((,class (:inherit 'font-lock-function-name-face))))
   `(org-column ((,class (:background ,gruvbox-dark0))))
   `(org-column-title ((,class (:background ,gruvbox-dark0 :underline t :weight bold))))
   `(org-warning ((,class (:foreground ,gruvbox-bright_red :weight bold :underline nil :bold t))))
   `(org-archived ((,class (:foreground ,gruvbox-light0 :weight bold))))
   `(org-link ((,class (:foreground ,gruvbox-faded_aqua :underline t))))
   `(org-footnote ((,class (:foreground ,gruvbox-bright_aqua :underline t))))
   `(org-ellipsis ((,class (:foreground ,gruvbox-light4))))
   `(org-date ((,class (:foreground ,gruvbox-bright_blue :underline t))))
   `(org-sexp-date ((,class (:foreground ,gruvbox-faded_blue :underline t))))
   `(org-tag ((,class (:bold t :weight bold))))
   `(org-list-dt ((,class (:bold t :weight bold))))
   `(org-todo ((,class (:foreground ,gruvbox-bright_red :weight bold :bold t))))
   `(org-done ((,class (:foreground ,gruvbox-bright_aqua :weight bold :bold t))))
   `(org-agenda-done ((,class (:foreground ,gruvbox-bright_aqua))))
   `(org-headline-done ((,class (:foreground ,gruvbox-bright_aqua))))
   `(org-table ((,class (:foreground ,gruvbox-bright_blue))))
   `(org-block ((,class (:background ,gruvbox-dark0_soft))))
   `(org-block-begin-line ((,class (:background ,gruvbox-dark1))))
   `(org-block-end-line ((,class (:background ,gruvbox-dark1))))
   `(org-formula ((,class (:foreground ,gruvbox-bright_yellow))))
   `(org-document-title ((,class (:foreground ,gruvbox-faded_blue))))
   `(org-document-info ((,class (:foreground ,gruvbox-faded_blue))))
   `(org-agenda-structure ((,class (:inherit 'font-lock-comment-face))))
   `(org-agenda-date-today ((,class (:foreground ,gruvbox-light0 :weight bold :italic t))))
   `(org-scheduled ((,class (:foreground ,gruvbox-bright_yellow))))
   `(org-scheduled-today ((,class (:foreground ,gruvbox-bright_blue))))
   `(org-scheduled-previously ((,class (:foreground ,gruvbox-faded_red))))
   `(org-upcoming-deadline ((,class (:inherit 'font-lock-keyword-face))))
   `(org-deadline-announce ((,class (:foreground ,gruvbox-faded_red))))
   `(org-time-grid ((,class (:foreground ,gruvbox-faded_orange))))
   `(org-latex-and-related ((,class (:foreground ,gruvbox-bright_blue))))
   `(org-habit-clear-face ((,class (:background ,gruvbox-faded_blue))))
   `(org-habit-clear-future-face ((,class (:background ,gruvbox-bright_blue))))
   `(org-habit-ready-face ((,class (:background ,gruvbox-faded_green))))
   `(org-habit-ready-future-face ((,class (:background ,gruvbox-bright_green))))
   `(org-habit-alert-face ((,class (:background ,gruvbox-faded_yellow))))
   `(org-habit-alert-future-face ((,class (:background ,gruvbox-bright_yellow))))
   `(org-habit-overdue-face ((,class (:background ,gruvbox-faded_red))))
   `(org-habit-overdue-future-face ((,class (:background ,gruvbox-bright_red))))

   ;; isearch
   `(isearch ((,class (:inherit hl-line))))
   `(lazy-highlight ((,class (:inherit match))))
   `(isearch-fail ((,class (:background ,gruvbox-faded_red))))

   ;; markdown-mode
   `(markdown-header-face-1 ((,class (:foreground ,gruvbox-bright_blue))))
   `(markdown-header-face-2 ((,class (:foreground ,gruvbox-bright_yellow))))
   `(markdown-header-face-3 ((,class (:foreground ,gruvbox-bright_purple))))
   `(markdown-header-face-4 ((,class (:foreground ,gruvbox-bright_red))))
   `(markdown-header-face-5 ((,class (:foreground ,gruvbox-bright_green))))
   `(markdown-header-face-6 ((,class (:foreground ,gruvbox-bright_aqua))))

   ;; anzu-mode
   `(anzu-mode-line ((,class (:foreground ,gruvbox-bright_yellow :weight bold))))
   `(anzu-match-1 ((,class (:background ,gruvbox-bright_green))))
   `(anzu-match-2 ((,class (:background ,gruvbox-faded_yellow))))
   `(anzu-match-3 ((,class (:background gruvbox-aquamarine4))))
   `(anzu-replace-to ((,class (:foreground ,gruvbox-bright_yellow))))
   `(anzu-replace-highlight ((,class (:inherit 'isearch))))

   ;; ido
   `(ido-only-match ((,class (:inherit 'success))))
   `(ido-first-match ((,class (:foreground ,gruvbox-light0_hard :weight bold :underline t))))
   `(ido-subdir ((,class (:inherit 'dired-directory))))

   ;; vertico
   `(vertico-current ((,class (:background ,gruvbox-dark0_soft :extend t))))

   ;; orderless
   `(orderless-match-face-0 ((,class (:inherit match))))
   `(orderless-match-face-1 ((,class (:inherit orderless-match-face-0))))
   `(orderless-match-face-2 ((,class (:inherit orderless-match-face-0))))
   `(orderless-match-face-3 ((,class (:inherit orderless-match-face-0))))

   ;; consult
   `(consult-line-number ((,class (:inherit line-number))))
   `(consult-line-number-wrapped ((,class (:inherit line-number))))
   `(consult-preview-match ((,class (:inherit hl-line))))
   `(consult-preview-line ((,class (:inherit hl-line))))

   ;; magit
   `(magit-bisect-bad ((,class (:foreground ,gruvbox-faded_red))))
   `(magit-bisect-good ((,class (:foreground ,gruvbox-faded_green))))
   `(magit-bisect-skip ((,class (:foreground ,gruvbox-faded_yellow))))
   `(magit-blame-heading ((,class (:foreground ,gruvbox-light0 :background ,gruvbox-dark2))))
   `(magit-branch-local ((,class (:foreground ,gruvbox-bright_blue))))
   `(magit-branch-current ((,class (:underline ,gruvbox-bright_blue :inherit 'magit-branch-local))))
   `(magit-branch-remote ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-cherry-equivalent ((,class (:foreground ,gruvbox-bright_purple))))
   `(magit-cherry-unmatched ((,class (:foreground ,gruvbox-bright_aqua))))
   `(magit-diff-added ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-diff-added-highlight ((,class (:foreground ,gruvbox-bright_green :inherit 'magit-diff-context-highlight))))
   `(magit-diff-base ((,class (:background ,gruvbox-faded_yellow :foreground ,gruvbox-light2))))
   `(magit-diff-base-highlight ((,class (:background ,gruvbox-faded_yellow :foreground ,gruvbox-light0))))
   `(magit-diff-context ((,class (:foreground ,gruvbox-dark1 :foreground ,gruvbox-light1))))
   `(magit-diff-context-highlight ((,class (:background ,gruvbox-dark1 :foreground ,gruvbox-light0))))
   `(magit-diff-hunk-heading ((,class (:background ,gruvbox-dark3 :foreground ,gruvbox-light2))))
   `(magit-diff-hunk-heading-highlight ((,class (:background ,gruvbox-dark2 :foreground ,gruvbox-light0))))
   `(magit-diff-hunk-heading-selection ((,class (:background ,gruvbox-dark2 :foreground ,gruvbox-bright_orange))))
   `(magit-diff-lines-heading ((,class (:background ,gruvbox-faded_orange :foreground ,gruvbox-light0))))
   `(magit-diff-removed ((,class (:foreground ,gruvbox-bright_red))))
   `(magit-diff-removed-highlight ((,class (:foreground ,gruvbox-bright_red :inherit 'magit-diff-context-highlight))))
   `(magit-diffstat-added ((,class (:foreground ,gruvbox-faded_green))))
   `(magit-diffstat-removed ((,class (:foreground ,gruvbox-faded_red))))
   `(magit-dimmed ((,class (:foreground ,gruvbox-dark4))))
   `(magit-hash ((,class (:foreground ,gruvbox-bright_blue))))
   `(magit-log-author ((,class (:foreground ,gruvbox-bright_red))))
   `(magit-log-date ((,class (:foreground ,gruvbox-bright_aqua))))
   `(magit-log-graph ((,class (:foreground ,gruvbox-dark4))))
   `(magit-process-ng ((,class (:foreground ,gruvbox-bright_red :weight bold))))
   `(magit-process-ok ((,class (:foreground ,gruvbox-bright_green :weight bold))))
   `(magit-reflog-amend ((,class (:foreground ,gruvbox-bright_purple))))
   `(magit-reflog-checkout ((,class (:foreground ,gruvbox-bright_blue))))
   `(magit-reflog-cherry-pick ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-reflog-commit ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-reflog-merge ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-reflog-other ((,class (:foreground ,gruvbox-bright_aqua))))
   `(magit-reflog-rebase ((,class (:foreground ,gruvbox-bright_purple))))
   `(magit-reflog-remote ((,class (:foreground ,gruvbox-bright_blue))))
   `(magit-reflog-reset ((,class (:foreground ,gruvbox-bright_red))))
   `(magit-refname ((,class (:foreground ,gruvbox-light4))))
   `(magit-section-heading ((,class (:foreground ,gruvbox-bright_yellow :weight bold))))
   `(magit-section-heading-selection ((,class (:foreground ,gruvbox-faded_yellow))))
   `(magit-section-highlight ((,class (:background ,gruvbox-dark1))))
   `(magit-sequence-drop ((,class (:foreground ,gruvbox-faded_yellow))))
   `(magit-sequence-head ((,class (:foreground ,gruvbox-bright_aqua))))
   `(magit-sequence-part ((,class (:foreground ,gruvbox-bright_yellow))))
   `(magit-sequence-stop ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-signature-bad ((,class (:foreground ,gruvbox-bright_red :weight bold))))
   `(magit-signature-error ((,class (:foreground ,gruvbox-bright_red))))
   `(magit-signature-expired ((,class (:foreground ,gruvbox-bright_orange))))
   `(magit-signature-good ((,class (:foreground ,gruvbox-bright_green))))
   `(magit-signature-revoked ((,class (:foreground ,gruvbox-bright_purple))))
   `(magit-signature-untrusted ((,class (:foreground ,gruvbox-bright_blue))))
   `(magit-tag ((,class (:foreground ,gruvbox-bright_yellow))))

   ;; cider
   `(cider-debug-code-overlay-face ((,class (:background ,gruvbox-dark2 :foreground ,gruvbox-light0))))
   `(cider-deprecated-face ((,class (:background ,gruvbox-dark2 :foreground ,gruvbox-bright_orange))))
   `(cider-enlightened-local-face ((,class (:foreground ,gruvbox-bright_orange :weight bold))))
   `(cider-error-highlight-face ((,class ((supports :underline (:style wave))) (:foreground ,gruvbox-bright_red :underline (:style wave)))))
   `(cider-fringe-good-face ((,class (:foreground ,gruvbox-neutral_green))))
   `(cider-instrumented-face ((,class (:background ,gruvbox-dark1))))
   `(cider-result-overlay-face ((,class (:background ,gruvbox-dark2))))
   `(cider-test-error-face ((,class (:background ,gruvbox-faded_red))))
   `(cider-test-error-face ((,class (:background ,gruvbox-neutral_orange))))
   `(cider-test-success-face ((,class (:background ,gruvbox-bright_green))))
   `(cider-traced ((,class (:background ,gruvbox-bright_aqua))))
   `(cider-warning-highlight-face ((,class (:foreground ,gruvbox-bright_yellow :underline (:style wave)))))

   ;; git-gutter
   `(git-gutter:modified ((,class (:background ,gruvbox-faded_blue :foreground ,gruvbox-faded_blue))))
   `(git-gutter:added ((,class (:background ,gruvbox-faded_green :foreground ,gruvbox-faded_green))))
   `(git-gutter:deleted ((,class (:background ,gruvbox-faded_red :foreground ,gruvbox-faded_red))))
   `(git-gutter+-modified ((,class (:foreground ,gruvbox-faded_blue :background ,gruvbox-faded_blue))))
   `(git-gutter+-added ((,class (:foreground ,gruvbox-faded_green :background ,gruvbox-faded_green))))
   `(git-gutter+-deleted ((,class (:foreground ,gruvbox-faded_red :background ,gruvbox-faded_red))))
   `(git-gutter-fr:modified ((,class (:inherit 'git-gutter:modified))))
   `(git-gutter-fr:added ((,class (:inherit 'git-gutter:added))))
   `(git-gutter-fr:deleted ((,class (:inherit 'git-gutter:deleted))))

   ;; diff-hl
   `(diff-hl-change ((,class (:background ,gruvbox-faded_blue :foreground ,gruvbox-faded_blue))))
   `(diff-hl-delete ((,class (:background ,gruvbox-faded_red :foreground ,gruvbox-faded_red))))
   `(diff-hl-insert ((,class (:background ,gruvbox-faded_green :foreground ,gruvbox-faded_green))))

   ;; langtool
   `(langtool-errline ((,class (:foreground ,gruvbox-dark0 :background ,gruvbox-bright_red))))
   `(langtool-correction-face ((,class (:foreground ,gruvbox-bright_yellow :weight bold))))

   ;; latex
   `(font-latex-bold-face ((,class (:foreground ,gruvbox-faded_green :bold t))))
   `(font-latex-italic-face ((,class (:foreground ,gruvbox-bright_green :underline t))))
   `(font-latex-math-face ((,class (:foreground ,gruvbox-light3))))
   `(font-latex-script-char-face ((,class (:foreground ,gruvbox-faded_aqua))))
   `(font-latex-sectioning-5-face ((,class (:foreground ,gruvbox-bright_yellow :bold t))))
   `(font-latex-sedate-face ((,class (:foreground ,gruvbox-light4))))
   `(font-latex-string-face ((,class (:foreground ,gruvbox-bright_orange))))
   `(font-latex-verbatim-face ((,class (:foreground ,gruvbox-light4))))
   `(font-latex-warning-face ((,class (:foreground ,gruvbox-bright_red :weight bold))))
   `(preview-face ((,class (:background ,gruvbox-dark1))))

   ;; lsp
   `(lsp-face-highlight-write ((,class (:inherit highlight))))
   `(lsp-face-highlight-read ((,class (:inherit lsp-face-highlight-write))))
   `(lsp-ui-doc-background ((,class (:background ,gruvbox-dark3))))
   `(lsp-ui-doc-header ((,class (:background ,gruvbox-faded_blue))))
   `(lsp-ui-peek-filename ((,class (:foreground ,gruvbox-bright_red))))
   `(lsp-ui-sideline-code-action ((,class (:foreground ,gruvbox-bright_yellow))))
   `(lsp-ui-sideline-current-symbol ((,class (:foreground ,gruvbox-faded_aqua))))
   `(lsp-ui-sideline-symbol ((,class (:foreground ,gruvbox-gray))))

   ;; dap
   `(dap-ui-marker-face ((,class (:inherit hl-line))))

   ;; mu4e
   `(mu4e-header-key-face ((,class (:foreground ,gruvbox-bright_green :weight bold))))
   `(mu4e-unread-face ((,class (:foreground ,gruvbox-bright_blue :weight bold))))
   `(mu4e-highlight-face ((,class (:foreground ,gruvbox-bright_green))))

   ;; shell script
   `(sh-quoted-exec ((,class (:foreground ,gruvbox-bright_purple))))
   `(sh-heredoc ((,class (:foreground ,gruvbox-bright_orange))))

   ;; undo-tree
   `(undo-tree-visualizer-active-branch-face ((,class (:foreground ,gruvbox-light0))))
   `(undo-tree-visualizer-current-face ((,class (:foreground ,gruvbox-bright_red))))
   `(undo-tree-visualizer-default-face ((,class (:foreground ,gruvbox-dark4))))
   `(undo-tree-visualizer-register-face ((,class (:foreground ,gruvbox-bright_yellow))))
   `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,gruvbox-bright_aqua))))

   ;; widget faces
   `(widget-button-pressed-face ((,class (:foreground ,gruvbox-bright_red))))
   `(widget-documentation-face ((,class (:foreground ,gruvbox-faded_green))))
   `(widget-field ((,class (:foreground ,gruvbox-light0 :background ,gruvbox-dark2))))
   `(widget-single-line-field ((,class (:foreground ,gruvbox-light0 :background ,gruvbox-dark2))))

   ;; dired
   `(dired-marked ((,class (:inherit match))))

   ;; dired+
   `(diredp-file-name ((,class (:foreground ,gruvbox-light2))))
   `(diredp-file-suffix ((,class (:foreground ,gruvbox-light4))))
   `(diredp-compressed-file-suffix ((,class (:foreground ,gruvbox-faded_blue))))
   `(diredp-dir-name ((,class (:foreground ,gruvbox-faded_blue))))
   `(diredp-dir-heading ((,class (:foreground ,gruvbox-bright_blue))))
   `(diredp-symlink ((,class (:foreground ,gruvbox-bright_orange))))
   `(diredp-date-time ((,class (:foreground ,gruvbox-light3))))
   `(diredp-number ((,class (:foreground ,gruvbox-faded_blue))))
   `(diredp-no-priv ((,class (:foreground ,gruvbox-dark4))))
   `(diredp-other-priv ((,class (:foreground ,gruvbox-dark2))))
   `(diredp-rare-priv ((,class (:foreground ,gruvbox-dark4))))
   `(diredp-ignored-file-name ((,class (:foreground ,gruvbox-dark4))))
   `(diredp-dir-priv ((,class (:foreground ,gruvbox-faded_blue :background gruvbox-dark_blue))))
   `(diredp-exec-priv ((,class (:foreground ,gruvbox-faded_blue :background gruvbox-dark_blue))))
   `(diredp-link-priv ((,class (:foreground ,gruvbox-faded_aqua :background ,gruvbox-dark_aqua))))
   `(diredp-read-priv ((,class (:foreground ,gruvbox-bright_red :background ,gruvbox-dark_red))))
   `(diredp-write-priv ((,class (:foreground ,gruvbox-bright_aqua :background ,gruvbox-dark_aqua))))

   ;; diredfl
   `(diredfl-autofile-name ((,class (:foreground ,gruvbox-light2))))
   `(diredfl-compressed-file-name ((,class (:foreground ,gruvbox-light2))))
   `(diredfl-compressed-file-suffix ((,class (:foreground ,gruvbox-faded_blue))))
   `(diredfl-date-time ((,class (:foreground ,gruvbox-bright_aqua))))
   `(diredfl-deletion ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(diredfl-deletion-file-name ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(diredfl-dir-heading ((,class (:foreground ,gruvbox-bright_blue :bold t))))
   `(diredfl-dir-name ((,class (:foreground ,gruvbox-bright_blue))))
   `(diredfl-dir-priv ((,class (:foreground ,gruvbox-bright_blue))))
   `(diredfl-exec-priv ((,class (:foreground ,gruvbox-bright_blue))))
   `(diredfl-executable-tag ((,class (:foreground ,gruvbox-bright_green))))
   `(diredfl-file-name ((,class (:foreground ,gruvbox-light2))))
   `(diredfl-file-suffix ((,class (:foreground ,gruvbox-light4))))
   `(diredfl-symlink ((,class (:foreground ,gruvbox-bright_purple))))
   `(diredfl-flag-mark ((,class (:foreground ,gruvbox-bright_yellow :background ,gruvbox-dark3))))
   `(diredfl-flag-mark-line ((,class (:foreground ,gruvbox-bright_yellow :background ,gruvbox-dark2))))
   `(diredfl-ignored-file-name ((,class (:foreground ,gruvbox-dark4))))
   `(diredfl-link-priv ((,class (:foreground ,gruvbox-faded_purple))))
   `(diredfl-no-priv ((,class (:foreground ,gruvbox-light2))))
   `(diredfl-number ((,class (:foreground ,gruvbox-bright_yellow))))
   `(diredfl-other-priv ((,class (:foreground ,gruvbox-bright_purple))))
   `(diredfl-rare-priv ((,class (:foreground ,gruvbox-light2))))
   `(diredfl-read-priv ((,class (:foreground ,gruvbox-bright_yellow))))
   `(diredfl-write-priv ((,class (:foreground ,gruvbox-bright_red))))
   `(diredfl-tagged-autofile-name ((,class (:foreground ,gruvbox-light4))))

   ;; eshell
   `(eshell-prompt ((,class (:foreground ,gruvbox-bright_aqua))))
   `(eshell-ls-archive ((,class (:foreground ,gruvbox-light3))))
   `(eshell-ls-backup ((,class (:foreground ,gruvbox-light4))))
   `(eshell-ls-clutter ((,class (:foreground ,gruvbox-bright_orange :weight bold))))
   `(eshell-ls-directory ((,class (:foreground ,gruvbox-bright_yellow))))
   `(eshell-ls-executable ((,class (:weight bold))))
   `(eshell-ls-missing ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(eshell-ls-product ((,class (:foreground ,gruvbox-faded_red))))
   `(eshell-ls-readonly ((,class (:foreground ,gruvbox-light2))))
   `(eshell-ls-special ((,class (:foreground ,gruvbox-bright_yellow :bold t))))
   `(eshell-ls-symlink ((,class (:foreground ,gruvbox-bright_red))))
   `(eshell-ls-unreadable ((,class (:foreground ,gruvbox-bright_red :bold t))))

   ;; wgrep
   `(wgrep-delete-face ((,class (:strike-through ,gruvbox-bright_red))))
   `(wgrep-done-face ((,class (:foreground ,gruvbox-turquoise4))))
   `(wgrep-face ((,class (:underline (:color ,gruvbox-bright_yellow :style line)))))
   `(wgrep-file-face ((,class (:inherit 'highlight))))
   `(wgrep-reject-face ((,class (:foreground ,gruvbox-bright_red :bold t))))

   ;; which-function-mode
   `(which-func ((,class (:foreground ,gruvbox-neutral_blue))))

   ;; hydra
   `(hydra-face-red ((,class (:foreground ,gruvbox-bright_red :weight bold))))
   `(hydra-face-blue ((,class (:foreground ,gruvbox-bright_blue :weight bold))))
   `(hydra-face-amaranth ((,class (:foreground ,gruvbox-bright_yellow :weight bold))))
   `(hydra-face-pink ((,class (:foreground ,gruvbox-bright_purple :weight bold))))
   `(hydra-face-teal ((,class (:foreground ,gruvbox-bright_aqua :weight bold))))

   ;; flycheck
   `(flycheck-warning ((,class (:underline (:style wave :color ,gruvbox-bright_yellow)))))
   `(flycheck-error ((,class (:underline (:style wave :color ,gruvbox-bright_red)))))
   `(flycheck-info ((,class (:underline (:style wave :color ,gruvbox-bright_blue)))))
   `(flycheck-fringe-warning ((,class (:foreground ,gruvbox-bright_yellow))))
   `(flycheck-fringe-error ((,class (:foreground ,gruvbox-bright_red))))
   `(flycheck-fringe-info ((,class (:foreground ,gruvbox-bright_blue))))
   `(flycheck-error-list-warning ((,class (:foreground ,gruvbox-bright_yellow :bold t))))
   `(flycheck-error-list-error ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(flycheck-error-list-info ((,class (:foreground ,gruvbox-bright_blue :bold t))))
   
   ;; flyspell
   `(flyspell-duplicate ((,class (:underline (:color ,gruvbox-light4 :style wave)))))
   `(flyspell-incorrect ((,class (:underline (:color ,gruvbox-bright_red :style wave)))))

   ;; erc
   `(erc-action-face ((,class (:inherit 'erc-default-face))))
   `(erc-bold-face ((,class (:weight bold))))
   `(erc-current-nick-face ((,class (:foreground gruvbox-aquamarine4))))
   `(erc-dangerous-host-face ((,class (:inherit 'font-lock-warning-face))))
   `(erc-default-face ((,class (:inherit 'default))))
   `(erc-direct-msg-face ((,class (:inherit 'erc-default-face))))
   `(erc-error-face ((,class (:inherit 'font-lock-warning-face))))
   `(erc-fool-face ((,class (:inherit 'erc-default-face))))
   `(erc-input-face ((,class (:foreground ,gruvbox-turquoise4))))
   `(erc-my-nick-face ((,class (:foreground ,gruvbox-turquoise4))))
   `(erc-nick-msg-face ((,class (:inherit 'erc-default-face))))
   `(erc-notice-face ((,class (:foreground ,gruvbox-dark4))))
   `(erc-timestamp-face ((,class (:foreground ,gruvbox-neutral_green))))
   `(erc-underline-face ((,class (:underline t))))
   `(erc-prompt-face ((,class (:foreground ,gruvbox-turquoise4))))
   `(erc-pal-face ((,class (:foreground ,gruvbox-neutral_yellow :weight bold))))
   `(erc-keyword-face ((,class (:foreground ,gruvbox-bright_orange :weight bold))))
   `(erc-nick-default-face ((,class (:weight 'regular))))
   `(erc-button ((,class (:weight bold :underline t))))

   ;; gnus
   `(gnus-group-mail-1 ((,class (:weight bold :foreground ,gruvbox-light0))))
   `(gnus-group-mail-2 ((,class (:inherit 'gnus-group-mail-1))))
   `(gnus-group-mail-3 ((,class (:inherit 'gnus-group-mail-1))))
   `(gnus-group-mail-1-empty ((,class (:foreground ,gruvbox-dark4))))
   `(gnus-group-mail-2-empty ((,class (:inherit 'gnus-group-mail-1-empty))))
   `(gnus-group-mail-3-empty ((,class (:inherit 'gnus-group-mail-1-empty))))
   `(gnus-group-news-1 ((,class (:inherit 'gnus-group-mail-1))))
   `(gnus-group-news-2 ((,class (:inherit 'gnus-group-news-1))))
   `(gnus-group-news-3 ((,class (:inherit 'gnus-group-news-1))))
   `(gnus-group-news-4 ((,class (:inherit 'gnus-group-news-1))))
   `(gnus-group-news-5 ((,class (:inherit 'gnus-group-news-1))))
   `(gnus-group-news-6 ((,class (:inherit 'gnus-group-news-1))))
   `(gnus-group-news-1-empty ((,class (:inherit 'gnus-group-mail-1-empty))))
   `(gnus-group-news-2-empty ((,class (:inherit 'gnus-group-news-1-empty))))
   `(gnus-group-news-3-empty ((,class (:inherit 'gnus-group-news-1-empty))))
   `(gnus-group-news-4-empty ((,class (:inherit 'gnus-group-news-1-empty))))
   `(gnus-group-news-5-empty ((,class (:inherit 'gnus-group-news-1-empty))))
   `(gnus-group-news-6-empty ((,class (:inherit 'gnus-group-news-1-empty))))
   `(gnus-group-mail-low ((,class (:inherit 'gnus-group-mail-1 :weight normal))))
   `(gnus-group-mail-low-empty ((,class (:inherit 'gnus-group-mail-1-empty))))
   `(gnus-group-news-low ((,class (:inherit 'gnus-group-mail-1 :foreground ,gruvbox-dark4))))
   `(gnus-group-news-low-empty ((,class (:inherit 'gnus-group-news-low :weight normal))))
   `(gnus-header-content ((,class (:inherit 'message-header-other))))
   `(gnus-header-from ((,class (:inherit 'message-header-other))))
   `(gnus-header-name ((,class (:inherit 'message-header-name))))
   `(gnus-header-newsgroups ((,class (:inherit 'message-header-other))))
   `(gnus-header-subject ((,class (:inherit 'message-header-subject))))
   `(gnus-summary-cancelled ((,class (:foreground ,gruvbox-bright_red :strike-through t))))
   `(gnus-summary-normal-ancient ((,class (:foreground ,gruvbox-dark4 :italic t))))
   `(gnus-summary-normal-read ((,class (:foreground ,gruvbox-light0))))
   `(gnus-summary-normal-ticked ((,class (:foreground ,gruvbox-bright_purple))))
   `(gnus-summary-normal-unread ((,class (:foreground ,gruvbox-bright_green :bold t))))
   `(gnus-summary-selected ((,class (:foreground ,gruvbox-bright_blue :weight bold))))
   `(gnus-cite-1 ((,class (:foreground ,gruvbox-bright_blue))))
   `(gnus-cite-2 ((,class (:foreground ,gruvbox-bright_green))))
   `(gnus-cite-3 ((,class (:foreground ,gruvbox-bright_yellow))))
   `(gnus-cite-4 ((,class (:foreground ,gruvbox-bright_purple))))
   `(gnus-cite-5 ((,class (:foreground ,gruvbox-faded_green))))
   `(gnus-cite-6 ((,class (:foreground ,gruvbox-faded_purple))))
   `(gnus-cite-7 ((,class (:foreground ,gruvbox-bright_orange))))
   `(gnus-cite-8 ((,class (:foreground ,gruvbox-burlywood4))))
   `(gnus-cite-9 ((,class (:foreground ,gruvbox-neutral_red))))
   `(gnus-cite-10 ((,class (:foreground ,gruvbox-neutral_aqua))))
   `(gnus-cite-11 ((,class (:foreground ,gruvbox-turquoise4))))
   `(gnus-signature ((,class (:foreground ,gruvbox-faded_orange))))
   `(gnus-x-face ((,class (:background ,gruvbox-dark4 :foreground ,gruvbox-light0))))

   ;; Proof General
   `(proof-active-area-face ((,class (:underline t))))
   `(proof-tacticals-name-face ((,class (:inherit 'font-lock-constant-face))))
   `(proof-tactics-name-face ((,class (:inherit 'font-lock-constant-face))))
   `(proof-locked-face ((,class (:background ,gruvbox-dark1))))
   `(proof-queue-face ((,class (:background ,gruvbox-dark2))))
   `(proof-warning-face ((,class (:background ,gruvbox-dark_red))))
   `(proof-error-face ((,class (:background ,gruvbox-bg :foreground ,gruvbox-faded_red))))

   ;; ledger-mode
   `(ledger-font-xact-highlight-face ((,class (:background ,gruvbox-dark1))))

   ;; Solaire
   `(solaire-default-face ((,class (:background ,gruvbox-dark0_soft))))
   `(solaire-minibuffer-face ((,class (:background ,gruvbox-dark0_soft))))
   `(solaire-hl-line-face ((,class (:background ,gruvbox-dark0_soft))))
   `(solaire-org-hide-face ((,class (:background ,gruvbox-dark0_soft))))

   ;; ansi-color <built-in>
   `(ansi-color-black ((,class (:foreground ,gruvbox-dark2 :background ,gruvbox-dark1))))
   `(ansi-color-red ((,class (:foreground ,gruvbox-bright_red :background ,gruvbox-bright_red))))
   `(ansi-color-green ((,class (:foreground ,gruvbox-bright_green :background ,gruvbox-bright_green))))
   `(ansi-color-yellow ((,class (:foreground ,gruvbox-bright_yellow :background ,gruvbox-bright_yellow))))
   `(ansi-color-blue ((,class (:foreground ,gruvbox-bright_blue :background ,gruvbox-bright_blue))))
   `(ansi-color-magenta ((,class (:foreground ,gruvbox-bright_purple :background ,gruvbox-bright_purple))))
   `(ansi-color-cyan ((,class (:foreground ,gruvbox-bright_aqua :background ,gruvbox-bright_aqua))))
   `(ansi-color-white ((,class (:foreground ,gruvbox-light1 :background ,gruvbox-light1))))
   `(ansi-color-bright-black ((,class (:foreground ,gruvbox-dark2 :background ,gruvbox-dark1))))
   `(ansi-color-bright-red ((,class (:foreground ,gruvbox-bright_red :background ,gruvbox-bright_red))))
   `(ansi-color-bright-green ((,class (:foreground ,gruvbox-bright_green :background ,gruvbox-bright_green))))
   `(ansi-color-bright-yellow ((,class (:foreground ,gruvbox-bright_yellow :background ,gruvbox-bright_yellow))))
   `(ansi-color-bright-blue ((,class (:foreground ,gruvbox-bright_blue :background ,gruvbox-bright_blue))))
   `(ansi-color-bright-magenta ((,class (:foreground ,gruvbox-bright_purple :background ,gruvbox-bright_purple))))
   `(ansi-color-bright-cyan ((,class (:foreground ,gruvbox-bright_aqua :background ,gruvbox-bright_aqua))))
   `(ansi-color-bright-white ((,class (:foreground ,gruvbox-light1 :background ,gruvbox-light1))))

   ;; Elpaca
   `(elpaca-finished ((,class (:foreground ,gruvbox-bright_green :bold t))))
   `(elpaca-blocked ((,class (:foreground ,gruvbox-bright_yellow :bold t))))
   `(elpaca-busy ((,class (:foreground ,gruvbox-bright_orange :bold t))))
   `(elpaca-failed ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(elpaca-ui-marked-delete ((,class (:foreground ,gruvbox-bright_red :bold t))))
   `(elpaca-ui-marked-fetch ((,class (:foreground ,gruvbox-bright_aqua :bold t))))
   `(elpaca-ui-marked-install ((,class (:foreground ,gruvbox-bright_blue :bold t))))
   `(elpaca-ui-marked-rebuild ((,class (:foreground ,gruvbox-bright_purple :bold t))))
   `(elpaca-ui-marked-update ((,class (:foreground ,gruvbox-bright_orange :bold t))))))

(provide-theme 'gruvbox)
