;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(file-name-history consult--grep-history))
(setq file-name-history '("~/.emacs.d/"))
(setq consult--grep-history '("#rc-var-file"))
